FROM osrf/ros:humble-desktop-full

ARG ROS_PACKAGE=ros_base \
    ROS_VERSION=humble \
    ROS_WS=ros2_ws

ENV ROS_DISTRO=${ROS_VERSION} \
    ROS_ROOT=/opt/ros/${ROS_VERSION} \
    ROS_PYTHON_VERSION=3 \
    RMW_IMPLEMENTATION=rmw_fastrtps_cpp \
    DEBIAN_FRONTEND=noninteractive \
    SHELL=/bin/bash

RUN apt-get update \
    && apt-get install -y \
    nano \
    && rm -rf /var/lib/apt/lists/*

ARG USERNAME=jet
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create a non-root user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && mkdir /home/$USERNAME/.config && chown $USER_UID:$USER_GID /home/$USERNAME/.config

# Set up sudo
RUN apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y jstest-gtk\
    usbutils \
    xxd \
    net-tools \
    iputils-ping \
    && rm -rf /ver/lib/apt/lists/*

# Download camera node and configurate it
RUN apt-get update \
    && apt install -y v4l-utils ros-humble-v4l2-camera ros-humble-image-transport-plugins \
    && usermod -aG video jet

USER root

RUN mkdir -p /${ROS_WS}/src \
    && chown -R ${USERNAME}:root /${ROS_WS}

COPY entrypoint.sh /entrypoint.sh
COPY bashrc_dev /home/${USERNAME}/.bashrc

ENTRYPOINT [ "/bin/bash",  "/entrypoint.sh"]

CMD ["bash"]